"""
Django settings for Boilerplate project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta
from decouple import config  

BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------------------------------------------------------------------
# SECURITY CONFIGURATION - For production, ensure these are properly configured!
# -----------------------------------------------------------------------------------------

#! SECURITY WARNING: Keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-j*+m6g*!yy7hl!xx&w7@gyjhkxutl_5)3g=b90)%dc$#&mzpa)', cast=str)

#! SECURITY WARNING: Don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

#! SECURITY WARNING: Don't allow all hosts in production
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1, localhost', cast=str).split(',')

# -----------------------------------------------------------------------------------------
#? APPLICATION CONFIGURATION
# -----------------------------------------------------------------------------------------

INSTALLED_APPS = [
    "jazzmin",  # Admin theme customizations
    "django.contrib.admin",  
    "django.contrib.auth",  
    "django.contrib.contenttypes",  
    "django.contrib.sessions",  
    "django.contrib.messages",  
    "django.contrib.staticfiles", 

    #? Your custom Django apps (Create these apps in the 'apps' folder) 
    #TODO: Change app name to apps.<app_name> in the apps.py file
    'apps.accounts',  # Custom app for user authentication
    'apps.core',  # Core functionalities (add more features as needed)
    'apps.payments',  # Handle payment system integration
    #? Add apps.<app_name>

    # Third-party apps
    'corsheaders',  # Cross-Origin Resource Sharing (CORS) to allow API requests from other domains
    'rest_framework',  # Django REST Framework for building APIs
    'rest_framework.authtoken',  # Token-based authentication
    'rest_framework_simplejwt',  # JSON Web Token (JWT) authentication
    'allauth',  # Authentication handler for login/signup
    'allauth.account',  # Account management via allauth
    'allauth.socialaccount.providers.google',  # Google social authentication
    'allauth.socialaccount',  # Social account management
    'dj_rest_auth',  # REST API endpoints for authentication
    'dj_rest_auth.registration',  # Registration endpoints for dj_rest_auth
    'social_django',  # Django OAuth authentication
    'django_filters',  # Django filter integration for API queries
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Enable CORS headers
    "django.middleware.security.SecurityMiddleware",  # Security middleware
    "django.contrib.sessions.middleware.SessionMiddleware",  # Session handling
    "django.middleware.common.CommonMiddleware",  # Common middleware (caching, etc.)
    "django.middleware.csrf.CsrfViewMiddleware",  # CSRF protection
    "django.contrib.auth.middleware.AuthenticationMiddleware",  # Authentication middleware
    "django.contrib.messages.middleware.MessageMiddleware",  # Messaging middleware
    "django.middleware.clickjacking.XFrameOptionsMiddleware",  # Clickjacking protection
]

ROOT_URLCONF = "Boilerplate.urls"  

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates", 
        "DIRS": [os.path.join(BASE_DIR, "templates")],  # Directories to search for templates 
        "APP_DIRS": True,  # Automatically look for templates in app directories
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",  
                "django.template.context_processors.request",  
                "django.contrib.auth.context_processors.auth",  
                "django.contrib.messages.context_processors.messages",  
            ],
        },
    },
]

WSGI_APPLICATION = "Boilerplate.wsgi.application"  

# -----------------------------------------------------------------------------------------
#? DATABASE CONFIGURATION
# -----------------------------------------------------------------------------------------

#TODO: Change to your production database configuration (use PostgreSQL for production)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",  # Change this to PostgreSQL or other databases
        "NAME": BASE_DIR / "db.sqlite3",  # Path to database file (for development)
    }
}

# -----------------------------------------------------------------------------------------
#? AUTHENTICATION CONFIGURATION
# -----------------------------------------------------------------------------------------

# Password validation settings (for securing user passwords)
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Custom user model (used for user-related features like authentication, profile, etc.)
AUTH_USER_MODEL = 'accounts.User'

# Password reset template
PASSWORD_RESET_EMAIL_HTML_TEMPLATE = 'password_reset_email.html'

# -----------------------------------------------------------------------------------------
# INTERNATIONALIZATION & TIMEZONE SETTINGS
# -----------------------------------------------------------------------------------------

LANGUAGE_CODE = "en-us"  # The default language for your project

TIME_ZONE = "UTC"  # Use UTC time for global support

USE_I18N = True  # Enable internationalization
USE_TZ = True  # Enable timezone support

# -----------------------------------------------------------------------------------------
#? STATIC & MEDIA FILES CONFIGURATION
# -----------------------------------------------------------------------------------------

# Static files management (e.g., CSS, JS)
STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR,'static'),]  # Add any directories where static files are located
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Media files management (e.g., images, user-uploaded files)
MEDIA_ROOT = 'media/'  # Folder to store media files on the server
MEDIA_URL = os.path.join(BASE_DIR, "media/")  # URL to access media files

# -----------------------------------------------------------------------------------------
#? JAZZMIN CONFIGURATION (for Django Admin UI Customization)
# -----------------------------------------------------------------------------------------

JAZZMIN_SETTINGS = {
    "site_title": "Admin Page",  # Title shown in the browser tab
    "site_header": "Backend Administration",  # Header shown on the admin page
    "site_brand": "Backend",  # Branding displayed at the top of the admin page
    #"site_logo": "images/logo.png",  # Path to your logo (ensure it's stored in static files)
    #"site_icon": "images/logo.png",  # Path to favicon
    "welcome_sign": "Welcome to the Django Admin Panel",  # Custom welcome message
    "copyright": "© 2025 Backend Inc.",  # Copyright footer text
    # Customizations for the login page
    #"login_logo": "images/logo.png",  # Logo for light mode
    "login_logo_dark": "images/logo_dark.png",  # Logo for dark mode
    # Theme and layout customizations
    "theme": "darkly",  # Dark theme for the admin interface
    "dark_mode": True,  # Enables dark mode by default
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Documentation", "url": "https://docs.myproject.com", "new_window": True},
    ],
}

# -----------------------------------------------------------------------------------------
#? THIRD-PARTY CONFIGURATIONS
# -----------------------------------------------------------------------------------------

# Email settings (used for sending verification, password reset emails, etc.)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')  # Your email address
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')  # Your email password

# Redis configuration (for caching, session storage, etc.)
REDIS_HOST = config('REDIS_HOST', default='localhost')
REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)
REDIS_DB = config('REDIS_DB', default=0, cast=int)

# REST framework & JWT settings
REST_USE_JWT = True
REST_AUTH_SERIALIZERS = {
    "USER_DETAILS_SERIALIZER": "accounts.serializers.CustomUserSerializer",
}

# CORS (Cross-Origin Resource Sharing) settings to allow certain domains to access your APIs
CORS_ALLOW_ALL_ORIGINS = True  # Allow all domains (change for security in production)
CORS_ALLOWS_CREDENTIALS = True

# Simple JWT (JSON Web Tokens) settings for authentication
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
}

# Social account providers for OAuth (e.g., Google authentication)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': config('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY', default=''),
            'secret': config('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET', default=''),
            'key': '',
        },
        "SCOPE": ["email", "profile"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}

# Django REST Framework settings (for configuring permissions, throttling, filters)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        #'dj_rest_auth.authentication.JWTCookieAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
    'DEFAULT_THROTTLE_CLASSES': ['rest_framework.throttling.AnonRateThrottle', 'rest_framework.throttling.UserRateThrottle'],
    'DEFAULT_THROTTLE_RATES': {'anon': '100/day', 'user': '1000/day'},
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}

# STRIPE CONFIG
STRIPE_TEST_SECRET_KEY = config("STRIPE_TEST_SECRET_KEY", default='your_stripe_test_secret_key')
STRIPE_TEST_PUBLISHABLE_KEY = config("STRIPE_TEST_PUBLISHABLE", default='your_stripe_test_publishable_key')

import dj_rest_auth